"""
CS Fundamentals Curriculum module.
This file contains well-curated Computer Science fundamental subjects to supplement the core curriculum.
These subjects are critical for BTech CS students and tech interviews.

To merge with the main curriculum, you can use the `get_full_curriculum()` helper at the bottom of this file.
"""

CURRICULUM_CS_FUNDAMENTALS = [
    {
        "name": "Data Structures & Algorithms",
        "description": "The most important subject for tech interviews.",
        "icon": "🧠",
        "topics": [
            {"title": "Algorithm analysis: Big O notation", "level": "Beginner"},
            {"title": "Algorithm analysis: Time complexity", "level": "Beginner"},
            {"title": "Algorithm analysis: Space complexity", "level": "Beginner"},
            {"title": "Algorithm analysis: Best, average, and worst cases", "level": "Beginner"},
            {"title": "Arrays: Declaration and initialization", "level": "Beginner"},
            {"title": "Arrays: Traversal", "level": "Beginner"},
            {"title": "Arrays: Insertion and deletion", "level": "Beginner"},
            {"title": "Arrays: Searching", "level": "Beginner"},
            {"title": "Arrays: Rotation", "level": "Beginner"},
            {"title": "Arrays: Prefix sums", "level": "Beginner"},
            {"title": "Strings: Basic operations", "level": "Beginner"},
            {"title": "Strings: Pattern matching basics", "level": "Beginner"},
            {"title": "Strings: Palindromes", "level": "Beginner"},
            {"title": "Strings: Anagram detection", "level": "Beginner"},
            {"title": "Searching: Linear search", "level": "Beginner"},
            {"title": "Searching: Binary search", "level": "Beginner"},
            {"title": "Searching: Binary search variations", "level": "Beginner"},
            {"title": "Basic sorting: Bubble sort", "level": "Beginner"},
            {"title": "Basic sorting: Selection sort", "level": "Beginner"},
            {"title": "Basic sorting: Insertion sort", "level": "Beginner"},
            {"title": "Basic sorting: Counting sort", "level": "Beginner"},
            {"title": "Recursion: Concept", "level": "Beginner"},
            {"title": "Recursion: Call stack", "level": "Beginner"},
            {"title": "Recursion: Base case", "level": "Beginner"},
            {"title": "Recursion: Recursive vs iterative", "level": "Beginner"},
            {"title": "Recursion: Simple problems (Factorial, Fibonacci, Power)", "level": "Beginner"},
            {"title": "Mathematics for DSA: GCD and LCM", "level": "Beginner"},
            {"title": "Mathematics for DSA: Prime numbers", "level": "Beginner"},
            {"title": "Mathematics for DSA: Sieve of Eratosthenes", "level": "Beginner"},
            {"title": "Mathematics for DSA: Modular arithmetic", "level": "Beginner"},

            {"title": "Linked Lists: Singly linked lists", "level": "Intermediate"},
            {"title": "Linked Lists: Doubly linked lists", "level": "Intermediate"},
            {"title": "Linked Lists: Circular linked lists", "level": "Intermediate"},
            {"title": "Linked Lists: Operations (Insert, delete, reverse)", "level": "Intermediate"},
            {"title": "Linked Lists: Detect cycle", "level": "Intermediate"},
            {"title": "Linked Lists: Merge", "level": "Intermediate"},
            {"title": "Stacks: Implementation", "level": "Intermediate"},
            {"title": "Stacks: Balanced parentheses", "level": "Intermediate"},
            {"title": "Stacks: Next greater element", "level": "Intermediate"},
            {"title": "Stacks: Stock span", "level": "Intermediate"},
            {"title": "Stacks: Infix and postfix", "level": "Intermediate"},
            {"title": "Queues: Implementation", "level": "Intermediate"},
            {"title": "Queues: Circular queue", "level": "Intermediate"},
            {"title": "Queues: Deque", "level": "Intermediate"},
            {"title": "Queues: Priority queue concept", "level": "Intermediate"},
            {"title": "Hashing: Hash tables", "level": "Intermediate"},
            {"title": "Hashing: Hash functions", "level": "Intermediate"},
            {"title": "Hashing: Collision handling (Chaining)", "level": "Intermediate"},
            {"title": "Hashing: Collision handling (Open addressing)", "level": "Intermediate"},
            {"title": "Hashing: Hash maps", "level": "Intermediate"},
            {"title": "Hashing: Hash sets", "level": "Intermediate"},
            {"title": "Trees: Binary tree basics", "level": "Intermediate"},
            {"title": "Trees: Traversals (Inorder, preorder, postorder)", "level": "Intermediate"},
            {"title": "Trees: Level-order traversal", "level": "Intermediate"},
            {"title": "Trees: BST basics", "level": "Intermediate"},
            {"title": "Trees: BST operations (Insert, delete, search)", "level": "Intermediate"},
            {"title": "Trees: Height and diameter", "level": "Intermediate"},
            {"title": "Heaps: Min heap", "level": "Intermediate"},
            {"title": "Heaps: Max heap", "level": "Intermediate"},
            {"title": "Heaps: Heapify", "level": "Intermediate"},
            {"title": "Heaps: Heap sort", "level": "Intermediate"},
            {"title": "Heaps: Priority queue implementation", "level": "Intermediate"},
            {"title": "Heaps: Kth largest and smallest", "level": "Intermediate"},
            {"title": "Sorting: Merge sort", "level": "Intermediate"},
            {"title": "Sorting: Quick sort", "level": "Intermediate"},
            {"title": "Sorting: Radix sort", "level": "Intermediate"},
            {"title": "Sorting: Comparisons", "level": "Intermediate"},
            {"title": "Two pointers technique", "level": "Intermediate"},
            {"title": "Sliding window technique", "level": "Intermediate"},
            {"title": "Recursion and backtracking: N-Queens", "level": "Intermediate"},
            {"title": "Recursion and backtracking: Sudoku solver", "level": "Intermediate"},
            {"title": "Recursion and backtracking: Permutations and subsets", "level": "Intermediate"},
            {"title": "Recursion and backtracking: Combination sum", "level": "Intermediate"},

            {"title": "Graphs: Representation (Adjacency list and matrix)", "level": "Pro"},
            {"title": "Graphs: BFS traversal", "level": "Pro"},
            {"title": "Graphs: DFS traversal", "level": "Pro"},
            {"title": "Graphs: Connected components", "level": "Pro"},
            {"title": "Graphs: Cycle detection", "level": "Pro"},
            {"title": "Graphs: Topological sort", "level": "Pro"},
            {"title": "Shortest path: Dijkstra's algorithm", "level": "Pro"},
            {"title": "Shortest path: Bellman-Ford algorithm", "level": "Pro"},
            {"title": "Shortest path: Floyd-Warshall algorithm", "level": "Pro"},
            {"title": "Minimum spanning tree: Kruskal's algorithm", "level": "Pro"},
            {"title": "Minimum spanning tree: Prim's algorithm", "level": "Pro"},
            {"title": "Dynamic Programming: Concept", "level": "Pro"},
            {"title": "Dynamic Programming: Memoization vs Tabulation", "level": "Pro"},
            {"title": "Dynamic Programming: 1D DP (Climbing stairs, House robber)", "level": "Pro"},
            {"title": "Dynamic Programming: 1D DP (Coin change)", "level": "Pro"},
            {"title": "Dynamic Programming: 2D DP (Longest common subsequence)", "level": "Pro"},
            {"title": "Dynamic Programming: 2D DP (Edit distance, 0/1 knapsack)", "level": "Pro"},
            {"title": "Dynamic Programming: DP on strings", "level": "Pro"},
            {"title": "Dynamic Programming: DP on grids", "level": "Pro"},
            {"title": "Greedy algorithms: Activity selection", "level": "Pro"},
            {"title": "Greedy algorithms: Fractional knapsack", "level": "Pro"},
            {"title": "Greedy algorithms: Huffman coding", "level": "Pro"},
            {"title": "Greedy algorithms: Interval scheduling", "level": "Pro"},
            {"title": "Divide and conquer: Merge sort analysis", "level": "Pro"},
            {"title": "Divide and conquer: Closest pair", "level": "Pro"},
            {"title": "Divide and conquer: Matrix multiplication", "level": "Pro"},
            {"title": "Tries: Implementation", "level": "Pro"},
            {"title": "Tries: Prefix search and autocomplete", "level": "Pro"},
            {"title": "Advanced trees: AVL tree concept", "level": "Pro"},
            {"title": "Advanced trees: Red-Black tree concept", "level": "Pro"},
            {"title": "Advanced trees: Segment trees", "level": "Pro"},
            {"title": "Advanced trees: Fenwick trees", "level": "Pro"},
            {"title": "Bit manipulation: Operators", "level": "Pro"},
            {"title": "Bit manipulation: Check, set, clear bits", "level": "Pro"},
            {"title": "Bit manipulation: Power of 2, counting set bits, XOR tricks", "level": "Pro"},
            {"title": "String algorithms: KMP algorithm", "level": "Pro"},
            {"title": "String algorithms: Rabin-Karp algorithm", "level": "Pro"},
            {"title": "String algorithms: Z-algorithm", "level": "Pro"},
            {"title": "Disjoint set union (Union-Find)", "level": "Pro"}
        ]
    },
    {
        "name": "Object-Oriented Programming",
        "description": "Critical concepts for writing clean, maintainable code.",
        "icon": "📦",
        "topics": [
            {"title": "What is OOP", "level": "Beginner"},
            {"title": "Procedural vs OOP", "level": "Beginner"},
            {"title": "Classes and objects", "level": "Beginner"},
            {"title": "Attributes and methods", "level": "Beginner"},
            {"title": "Constructors: Default", "level": "Beginner"},
            {"title": "Constructors: Parameterized", "level": "Beginner"},
            {"title": "Constructors: Copy", "level": "Beginner"},
            {"title": "The `this` / `self` keyword", "level": "Beginner"},
            {"title": "Access modifiers: Public", "level": "Beginner"},
            {"title": "Access modifiers: Private", "level": "Beginner"},
            {"title": "Access modifiers: Protected", "level": "Beginner"},
            {"title": "Getters and setters (Encapsulation)", "level": "Beginner"},
            {"title": "Static variables", "level": "Beginner"},
            {"title": "Static methods", "level": "Beginner"},
            {"title": "Method overloading", "level": "Beginner"},

            {"title": "Inheritance: Single", "level": "Intermediate"},
            {"title": "Inheritance: Multilevel", "level": "Intermediate"},
            {"title": "Inheritance: Hierarchical", "level": "Intermediate"},
            {"title": "Method overriding", "level": "Intermediate"},
            {"title": "Super/parent class constructor calling", "level": "Intermediate"},
            {"title": "Abstract classes", "level": "Intermediate"},
            {"title": "Abstract methods", "level": "Intermediate"},
            {"title": "Interfaces", "level": "Intermediate"},
            {"title": "Polymorphism: Compile-time", "level": "Intermediate"},
            {"title": "Polymorphism: Runtime", "level": "Intermediate"},
            {"title": "Composition vs Inheritance", "level": "Intermediate"},
            {"title": "Association relationship", "level": "Intermediate"},
            {"title": "Aggregation relationship", "level": "Intermediate"},
            {"title": "Composition relationship", "level": "Intermediate"},
            {"title": "Exception handling in OOP", "level": "Intermediate"},

            {"title": "SOLID Principles: Single Responsibility Principle (SRP)", "level": "Pro"},
            {"title": "SOLID Principles: Open-Closed Principle (OCP)", "level": "Pro"},
            {"title": "SOLID Principles: Liskov Substitution Principle (LSP)", "level": "Pro"},
            {"title": "SOLID Principles: Interface Segregation Principle (ISP)", "level": "Pro"},
            {"title": "SOLID Principles: Dependency Inversion Principle (DIP)", "level": "Pro"},
            {"title": "Design patterns: Singleton", "level": "Pro"},
            {"title": "Design patterns: Factory", "level": "Pro"},
            {"title": "Design patterns: Observer", "level": "Pro"},
            {"title": "Design patterns: Strategy", "level": "Pro"},
            {"title": "Design patterns: Decorator", "level": "Pro"},
            {"title": "Design patterns: Adapter", "level": "Pro"},
            {"title": "Design patterns: Builder", "level": "Pro"},
            {"title": "Design patterns: Command", "level": "Pro"},
            {"title": "Design patterns: State", "level": "Pro"},
            {"title": "Dependency injection", "level": "Pro"},
            {"title": "UML class diagrams", "level": "Pro"},
            {"title": "Clean code principles", "level": "Pro"}
        ]
    },
    {
        "name": "Operating Systems",
        "description": "Systems understanding for backend engineering and computing.",
        "icon": "🖥️",
        "topics": [
            {"title": "What is an OS", "level": "Beginner"},
            {"title": "Types of OS", "level": "Beginner"},
            {"title": "System calls", "level": "Beginner"},
            {"title": "Kernel mode vs User mode", "level": "Beginner"},
            {"title": "Process concept", "level": "Beginner"},
            {"title": "Process Control Block (PCB)", "level": "Beginner"},
            {"title": "Process states", "level": "Beginner"},
            {"title": "Process creation: fork and exec", "level": "Beginner"},
            {"title": "Threads vs Processes", "level": "Beginner"},
            {"title": "CPU scheduling: FCFS", "level": "Beginner"},
            {"title": "CPU scheduling: SJF", "level": "Beginner"},
            {"title": "CPU scheduling: Priority", "level": "Beginner"},
            {"title": "CPU scheduling: Round Robin", "level": "Beginner"},
            {"title": "Scheduling criteria: Turnaround, waiting, response time", "level": "Beginner"},
            {"title": "Inter-process communication: Pipes", "level": "Beginner"},
            {"title": "Inter-process communication: Shared memory", "level": "Beginner"},
            {"title": "Inter-process communication: Message passing", "level": "Beginner"},

            {"title": "Process synchronization: Race condition", "level": "Intermediate"},
            {"title": "Process synchronization: Critical section", "level": "Intermediate"},
            {"title": "Synchronization tools: Mutex", "level": "Intermediate"},
            {"title": "Synchronization tools: Semaphore", "level": "Intermediate"},
            {"title": "Synchronization tools: Monitors", "level": "Intermediate"},
            {"title": "Classic sync problems: Producer-Consumer", "level": "Intermediate"},
            {"title": "Classic sync problems: Readers-Writers", "level": "Intermediate"},
            {"title": "Classic sync problems: Dining Philosophers", "level": "Intermediate"},
            {"title": "Deadlocks: Conditions", "level": "Intermediate"},
            {"title": "Deadlocks: Prevention", "level": "Intermediate"},
            {"title": "Deadlocks: Avoidance (Banker's algorithm)", "level": "Intermediate"},
            {"title": "Deadlocks: Detection", "level": "Intermediate"},
            {"title": "Deadlocks: Recovery", "level": "Intermediate"},
            {"title": "Memory management: Contiguous allocation", "level": "Intermediate"},
            {"title": "Memory management: Paging", "level": "Intermediate"},
            {"title": "Memory management: Segmentation", "level": "Intermediate"},
            {"title": "Virtual memory: Demand paging", "level": "Intermediate"},
            {"title": "Virtual memory: Page replacement (FIFO)", "level": "Intermediate"},
            {"title": "Virtual memory: Page replacement (LRU)", "level": "Intermediate"},
            {"title": "Virtual memory: Page replacement (Optimal)", "level": "Intermediate"},
            {"title": "Virtual memory: Thrashing", "level": "Intermediate"},
            {"title": "Virtual memory: Working set", "level": "Intermediate"},
            {"title": "Memory allocation strategies: First fit, best fit, worst fit", "level": "Intermediate"},

            {"title": "File systems: File concept", "level": "Pro"},
            {"title": "File systems: Directory structure", "level": "Pro"},
            {"title": "File systems: Allocation methods (Contiguous, linked, indexed)", "level": "Pro"},
            {"title": "Free space management", "level": "Pro"},
            {"title": "Disk scheduling: FCFS", "level": "Pro"},
            {"title": "Disk scheduling: SSTF", "level": "Pro"},
            {"title": "Disk scheduling: SCAN and C-SCAN", "level": "Pro"},
            {"title": "Disk scheduling: LOOK", "level": "Pro"},
            {"title": "RAID levels", "level": "Pro"},
            {"title": "I/O management", "level": "Pro"},
            {"title": "Device drivers", "level": "Pro"},
            {"title": "Protection and security: Access matrix", "level": "Pro"},
            {"title": "Protection and security: Capability lists", "level": "Pro"},
            {"title": "Linux commands basics", "level": "Pro"},
            {"title": "Linux shell basics", "level": "Pro"},
            {"title": "Real-time operating systems", "level": "Pro"},
            {"title": "Virtualization concepts", "level": "Pro"}
        ]
    },
    {
        "name": "Computer Networks",
        "description": "Fundamentals of networking and how the internet works.",
        "icon": "🌐",
        "topics": [
            {"title": "What is a computer network", "level": "Beginner"},
            {"title": "Types of networks: LAN, WAN, MAN", "level": "Beginner"},
            {"title": "Network topologies: Star, bus, ring, mesh", "level": "Beginner"},
            {"title": "OSI model overview", "level": "Beginner"},
            {"title": "OSI Layer: Physical", "level": "Beginner"},
            {"title": "OSI Layer: Data Link", "level": "Beginner"},
            {"title": "OSI Layer: Network", "level": "Beginner"},
            {"title": "OSI Layer: Transport", "level": "Beginner"},
            {"title": "OSI Layer: Session", "level": "Beginner"},
            {"title": "OSI Layer: Presentation", "level": "Beginner"},
            {"title": "OSI Layer: Application", "level": "Beginner"},
            {"title": "TCP/IP model overview", "level": "Beginner"},
            {"title": "TCP/IP model layers", "level": "Beginner"},
            {"title": "OSI vs TCP/IP comparison", "level": "Beginner"},
            {"title": "IP addressing: IPv4", "level": "Beginner"},
            {"title": "IP addressing: Classes", "level": "Beginner"},
            {"title": "IP addressing: Subnet masks", "level": "Beginner"},
            {"title": "Subnetting", "level": "Beginner"},
            {"title": "Classless Inter-Domain Routing (CIDR)", "level": "Beginner"},
            {"title": "Physical layer: Transmission media", "level": "Beginner"},
            {"title": "Physical layer: Encoding", "level": "Beginner"},

            {"title": "Data link layer: Framing", "level": "Intermediate"},
            {"title": "Data link layer: Error detection (CRC, checksum)", "level": "Intermediate"},
            {"title": "Data link layer: Error correction (Hamming code)", "level": "Intermediate"},
            {"title": "Flow control: Stop-and-wait", "level": "Intermediate"},
            {"title": "Flow control: Sliding window (Go-Back-N, Selective Repeat)", "level": "Intermediate"},
            {"title": "MAC protocols: CSMA/CD", "level": "Intermediate"},
            {"title": "MAC protocols: CSMA/CA", "level": "Intermediate"},
            {"title": "MAC protocols: ALOHA", "level": "Intermediate"},
            {"title": "Switching: Circuit switching", "level": "Intermediate"},
            {"title": "Switching: Packet switching", "level": "Intermediate"},
            {"title": "Switching: Message switching", "level": "Intermediate"},
            {"title": "Network layer: Routing algorithms (Distance vector)", "level": "Intermediate"},
            {"title": "Network layer: Routing algorithms (Link state)", "level": "Intermediate"},
            {"title": "Routing protocols: RIP", "level": "Intermediate"},
            {"title": "Routing protocols: OSPF", "level": "Intermediate"},
            {"title": "Routing protocols: BGP", "level": "Intermediate"},
            {"title": "Network Address Translation (NAT)", "level": "Intermediate"},
            {"title": "Dynamic Host Configuration Protocol (DHCP)", "level": "Intermediate"},
            {"title": "Address Resolution Protocol (ARP)", "level": "Intermediate"},
            {"title": "Internet Control Message Protocol (ICMP)", "level": "Intermediate"},
            {"title": "Transport layer: TCP vs UDP", "level": "Intermediate"},
            {"title": "Transport layer: TCP handshake", "level": "Intermediate"},
            {"title": "Transport layer: Congestion control (Slow start, congestion avoidance)", "level": "Intermediate"},

            {"title": "Application layer: DNS", "level": "Pro"},
            {"title": "Application layer: HTTP/HTTPS", "level": "Pro"},
            {"title": "Application layer: FTP", "level": "Pro"},
            {"title": "Application layer: SMTP, POP3, IMAP", "level": "Pro"},
            {"title": "HTTP methods", "level": "Pro"},
            {"title": "HTTP status codes", "level": "Pro"},
            {"title": "REST principles", "level": "Pro"},
            {"title": "WebSockets", "level": "Pro"},
            {"title": "HTTP/2", "level": "Pro"},
            {"title": "HTTP/3 (QUIC)", "level": "Pro"},
            {"title": "Network security: Firewalls", "level": "Pro"},
            {"title": "Network security: VPN", "level": "Pro"},
            {"title": "Network security: SSL/TLS", "level": "Pro"},
            {"title": "Network security: Certificates", "level": "Pro"},
            {"title": "Cryptography basics: Symmetric and asymmetric", "level": "Pro"},
            {"title": "Cryptography basics: Hashing", "level": "Pro"},
            {"title": "Email security", "level": "Pro"},
            {"title": "DNS security", "level": "Pro"},
            {"title": "Content Delivery Network (CDN)", "level": "Pro"},
            {"title": "Load balancing", "level": "Pro"},
            {"title": "Reverse proxy", "level": "Pro"},
            {"title": "Socket programming concepts", "level": "Pro"},
            {"title": "IPv6", "level": "Pro"},
            {"title": "IoT networking basics", "level": "Pro"}
        ]
    },
    {
        "name": "Database Management Systems",
        "description": "The theory and architecture behind relational and non-relational databases.",
        "icon": "🗄️",
        "topics": [
            {"title": "What is a DBMS", "level": "Beginner"},
            {"title": "File system vs DBMS", "level": "Beginner"},
            {"title": "Data models: Hierarchical, network, relational", "level": "Beginner"},
            {"title": "ER model: Entities and attributes", "level": "Beginner"},
            {"title": "ER model: Relationships", "level": "Beginner"},
            {"title": "ER diagrams: Cardinality", "level": "Beginner"},
            {"title": "ER diagrams: Participation", "level": "Beginner"},
            {"title": "ER diagrams: Generalization and specialization", "level": "Beginner"},
            {"title": "Relational model: Tuples, attributes, domains, schemas", "level": "Beginner"},
            {"title": "Keys: Super key", "level": "Beginner"},
            {"title": "Keys: Candidate key", "level": "Beginner"},
            {"title": "Keys: Primary key", "level": "Beginner"},
            {"title": "Keys: Foreign key", "level": "Beginner"},
            {"title": "Keys: Composite key", "level": "Beginner"},
            {"title": "Relational algebra: Selection", "level": "Beginner"},
            {"title": "Relational algebra: Projection", "level": "Beginner"},
            {"title": "Relational algebra: Join", "level": "Beginner"},
            {"title": "Relational algebra: Union, intersection, difference", "level": "Beginner"},

            {"title": "Functional dependencies", "level": "Intermediate"},
            {"title": "Normalization: 1NF", "level": "Intermediate"},
            {"title": "Normalization: 2NF", "level": "Intermediate"},
            {"title": "Normalization: 3NF", "level": "Intermediate"},
            {"title": "Normalization: BCNF", "level": "Intermediate"},
            {"title": "Normalization: 4NF", "level": "Intermediate"},
            {"title": "Denormalization", "level": "Intermediate"},
            {"title": "Transactions: ACID properties", "level": "Intermediate"},
            {"title": "Transaction states", "level": "Intermediate"},
            {"title": "Transaction schedules", "level": "Intermediate"},
            {"title": "Concurrency control: Lock-based (shared, exclusive)", "level": "Intermediate"},
            {"title": "Concurrency control: Two-phase locking", "level": "Intermediate"},
            {"title": "Timestamp-based protocols", "level": "Intermediate"},
            {"title": "Deadlock in transactions", "level": "Intermediate"},
            {"title": "Recovery: Log-based", "level": "Intermediate"},
            {"title": "Recovery: Checkpoints", "level": "Intermediate"},
            {"title": "Recovery: Shadow paging", "level": "Intermediate"},

            {"title": "Indexing: Primary and secondary", "level": "Pro"},
            {"title": "Indexing: Dense and sparse", "level": "Pro"},
            {"title": "B-tree indexing", "level": "Pro"},
            {"title": "B+ tree indexing", "level": "Pro"},
            {"title": "Hashing in databases", "level": "Pro"},
            {"title": "Query processing", "level": "Pro"},
            {"title": "Query optimization", "level": "Pro"},
            {"title": "Joins: Nested loop", "level": "Pro"},
            {"title": "Joins: Sort-merge", "level": "Pro"},
            {"title": "Joins: Hash join", "level": "Pro"},
            {"title": "NoSQL concepts: Document, key-value", "level": "Pro"},
            {"title": "NoSQL concepts: Columnar, graph databases", "level": "Pro"},
            {"title": "CAP theorem", "level": "Pro"},
            {"title": "ACID vs BASE", "level": "Pro"},
            {"title": "Database sharding and partitioning", "level": "Pro"},
            {"title": "Replication strategies", "level": "Pro"},
            {"title": "Data warehousing and OLAP", "level": "Pro"}
        ]
    },
    {
        "name": "C Programming",
        "description": "Essential low-level programming language for understanding systems.",
        "icon": "C",
        "topics": [
            {"title": "What is C, history, compilation process", "level": "Beginner"},
            {"title": "Data types: int, float, char, double", "level": "Beginner"},
            {"title": "Variables, constants, literals", "level": "Beginner"},
            {"title": "Input/output: printf, scanf, format specifiers", "level": "Beginner"},
            {"title": "Operators: Arithmetic", "level": "Beginner"},
            {"title": "Operators: Relational, logical", "level": "Beginner"},
            {"title": "Operators: Bitwise, assignment", "level": "Beginner"},
            {"title": "Control flow: if, if-else, nested if", "level": "Beginner"},
            {"title": "Control flow: switch", "level": "Beginner"},
            {"title": "Loops: for", "level": "Beginner"},
            {"title": "Loops: while, do-while", "level": "Beginner"},
            {"title": "Loops: break, continue", "level": "Beginner"},
            {"title": "Functions: Declaration and definition", "level": "Beginner"},
            {"title": "Functions: Calling and return values", "level": "Beginner"},
            {"title": "Function parameters: Pass by value", "level": "Beginner"},
            {"title": "Scope and lifetime of variables", "level": "Beginner"},
            {"title": "Storage classes: auto, static", "level": "Beginner"},
            {"title": "Storage classes: extern, register", "level": "Beginner"},

            {"title": "Arrays: 1D declaration and initialization", "level": "Intermediate"},
            {"title": "Arrays: 1D traversal", "level": "Intermediate"},
            {"title": "Arrays: 2D arrays, matrix operations", "level": "Intermediate"},
            {"title": "Strings in C: Character arrays", "level": "Intermediate"},
            {"title": "Strings in C: string functions (strlen, strcpy, strcmp, strcat)", "level": "Intermediate"},
            {"title": "Pointers: Concept and declaration", "level": "Intermediate"},
            {"title": "Pointers: Dereferencing", "level": "Intermediate"},
            {"title": "Pointers: Pointer arithmetic", "level": "Intermediate"},
            {"title": "Pointers: Pointers and arrays", "level": "Intermediate"},
            {"title": "Pointers: Pointer to pointer", "level": "Intermediate"},
            {"title": "Pointers: Function pointers", "level": "Intermediate"},
            {"title": "Dynamic memory allocation: malloc, calloc", "level": "Intermediate"},
            {"title": "Dynamic memory allocation: realloc, free", "level": "Intermediate"},
            {"title": "Structures: Definition and initialization", "level": "Intermediate"},
            {"title": "Structures: Nested structures", "level": "Intermediate"},
            {"title": "Unions", "level": "Intermediate"},
            {"title": "Enumerations", "level": "Intermediate"},
            {"title": "Typedef", "level": "Intermediate"},
            {"title": "Pass by reference using pointers", "level": "Intermediate"},
            {"title": "File handling: fopen, fclose", "level": "Intermediate"},
            {"title": "File handling: fprintf, fscanf", "level": "Intermediate"},
            {"title": "File handling: fread, fwrite", "level": "Intermediate"},

            {"title": "Preprocessor directives: #define, #include", "level": "Pro"},
            {"title": "Preprocessor directives: #ifdef, conditionals", "level": "Pro"},
            {"title": "Macros: Function-like macros", "level": "Pro"},
            {"title": "Macros: Macro pitfalls", "level": "Pro"},
            {"title": "Command line arguments: argc, argv", "level": "Pro"},
            {"title": "Recursion in C: Tower of Hanoi", "level": "Pro"},
            {"title": "Recursion in C: Merge sort implementation", "level": "Pro"},
            {"title": "Linked list implementation in C", "level": "Pro"},
            {"title": "Stack implementation in C", "level": "Pro"},
            {"title": "Queue implementation in C", "level": "Pro"},
            {"title": "Binary tree implementation in C", "level": "Pro"},
            {"title": "Memory layout: Stack and heap", "level": "Pro"},
            {"title": "Memory layout: Data and text segments", "level": "Pro"},
            {"title": "Memory leaks and debugging", "level": "Pro"},
            {"title": "Volatile and const qualifiers", "level": "Pro"},
            {"title": "Bit manipulation in C", "level": "Pro"},
            {"title": "Multi-file programs: Header files", "level": "Pro"},
            {"title": "Multi-file programs: Linking", "level": "Pro"},
            {"title": "Makefiles", "level": "Pro"}
        ]
    }
]

# Merge helper
def get_full_curriculum():
    """Returns the complete curriculum including CS fundamentals."""
    try:
        from curriculum import CURRICULUM
        return CURRICULUM + CURRICULUM_CS_FUNDAMENTALS
    except ImportError:
        return CURRICULUM_CS_FUNDAMENTALS
